// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */
enum TokenTypeEnum {
  SYNTH,
  WAVE,
  ART,
  ORDER
}

enum SynthTypeEnum {
  FESTIVAL,
  CONCERT,
  TOUR,
  CONFERENCE,
  OTHER
}

enum WaveTypeEnum {
  MUSIC,
  ART,
  FILM,
  GAME,
  BOOK,
  OTHER,
  SPORT
}

enum ArtTypeEnum {
  ABSTRACT,
  REALISM,
  SURREALISM,
  IMPRESSIONISM,
  EXPRESSIONISM,
  FIGURATIVE,
  CONTEMPORARY,
  MODERN,
  OTHER
}

enum OrderTypeEnum {
  DASHIKI,
  TSHIRT,
  POSTER,
  HOODIE,
  HAT,
  MARKER,
  CRAYON,
  PENCIL
}

enum TransferStatusEnum {
  IDLE,
  PENDING,
  COMPLETE,
  FAILED,
  CANCELLED
}
