// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { SynthContract, SynthContractData, SynthContractTableId } from "./tables/SynthContract.sol";
import { WaveContract, WaveContractData, WaveContractTableId } from "./tables/WaveContract.sol";
import { WaveAttributes, WaveAttributesData, WaveAttributesTableId } from "./tables/WaveAttributes.sol";
import { ArtContract, ArtContractData, ArtContractTableId } from "./tables/ArtContract.sol";
import { Order, OrderData, OrderTableId } from "./tables/Order.sol";
import { WavesAddrs, WavesAddrsTableId } from "./tables/WavesAddrs.sol";
import { OrderTokenAddrs, OrderTokenAddrsTableId } from "./tables/OrderTokenAddrs.sol";
import { WaveResolverAddrs, WaveResolverAddrsTableId } from "./tables/WaveResolverAddrs.sol";
import { SynthAccountImplAddrs, SynthAccountImplAddrsTableId } from "./tables/SynthAccountImplAddrs.sol";
import { Asset, AssetData, AssetTableId } from "./tables/Asset.sol";
import { Identity, IdentityData, IdentityTableId } from "./tables/Identity.sol";
import { TransferStatus, TransferStatusTableId } from "./tables/TransferStatus.sol";
import { Owner, OwnerTableId } from "./tables/Owner.sol";
import { Artist, ArtistTableId } from "./tables/Artist.sol";
import { Creative, CreativeTableId } from "./tables/Creative.sol";
import { Organizer, OrganizerTableId } from "./tables/Organizer.sol";
import { Token, TokenData, TokenTableId } from "./tables/Token.sol";
import { Counter, CounterTableId } from "./tables/Counter.sol";
