// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { ArtTypeEnum } from "./../common.sol";

/**
 * @title IArtSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IArtSystem {
  function createArt(
    address artist,
    ArtTypeEnum artType,
    string memory name,
    string memory metadata,
    string memory script,
    string memory image
  ) external;

  function modifyArt(
    address art,
    ArtTypeEnum artType,
    string memory metadata,
    string memory script,
    string memory image
  ) external;

  function mintArtToken(address art, address synth, address account) external;
}
