// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { OrderTypeEnum, TransferStatusEnum } from "./../common.sol";

/**
 * @title IOrderSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IOrderSystem {
  error NotWavesAccount();

  function createOrder(OrderTypeEnum orderType, bytes32 artId, address owner, string memory metadata) external;

  function modifyOrder(bytes32 orderId, TransferStatusEnum transferStatus, string memory metadata) external;

  function cancelOrder(bytes32 orderId) external;
}
