// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { SynthTypeEnum } from "./../common.sol";

/**
 * @title ISynthSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ISynthSystem {
  error AlreadyExists();

  function createSynth(
    SynthTypeEnum synthType,
    address organizer,
    string memory name,
    string memory metadata,
    address[] memory artWhitelist,
    address[] memory waveWhitelist,
    address[] memory ticketWhitelist
  ) external;

  function modifySynth(address synth, SynthTypeEnum synthType, string memory metadata) external;

  function mintSynthToken(address synth, address ticket) external;

  function addToArtWhitelist(address synth, address art) external;

  function removeFromArtWhitelist(address synth, address art) external;

  function addToTicketWhitelist(address synth, address ticket) external;

  function removeFromTicketWhitelist(address synth, address ticket) external;

  function addWave(address synth, address wave) external;

  function removeWave(address synth, address wave) external;
}
