// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { TokenTypeEnum } from "./../common.sol";

/**
 * @title ITokenSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ITokenSystem {
  function mint(TokenTypeEnum tokenType, address token, address to) external returns (uint256);

  function burn(TokenTypeEnum tokenType, address token, uint256 tokenId) external;
}
