// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/codegen/interfaces/IBaseWorld.sol";

import { IArtSystem } from "./IArtSystem.sol";
import { IIncrementSystem } from "./IIncrementSystem.sol";
import { IInitSystem } from "./IInitSystem.sol";
import { IOrderSystem } from "./IOrderSystem.sol";
import { ISynthSystem } from "./ISynthSystem.sol";
import { ITokenSystem } from "./ITokenSystem.sol";
import { IWaveSystem } from "./IWaveSystem.sol";

/**
 * @title IWorld
 * @notice This interface integrates all systems and associated function selectors
 * that are dynamically registered in the World during deployment.
 * @dev This is an autogenerated file; do not edit manually.
 */
interface IWorld is
  IBaseWorld,
  IArtSystem,
  IIncrementSystem,
  IInitSystem,
  IOrderSystem,
  ISynthSystem,
  ITokenSystem,
  IWaveSystem
{

}
