const SYNTH_REGISTRY_ADDRESS = "0x";

const COACHELLA_2024_TICKET_ADDRESS = "0x";
const LOLLAPALOOZA_CHICAGO_2024_TICKET_ADDRESS = "0x";

const COACHELLA_2024_SYNTH_GENERATOR_ADDRESS = "0x";
const LOLLAPALOOZA_CHICAGO_2024_SYNTH_GENERATOR_ADDRESS = "0x";

const COACHELLA_2024_WAVES_ADDRESS = "0x";
const LOLLAPALOOZA_CHICAGO_2024_WAVES_ADDRESS = "0x";
