export const mockSynths: Synth[] = [
  {
    address: "0x0000000000",
    eventName: "Coachella",
    tokenAddress: "0x0000000000",
    tokenId: 0,
    image: "assets/mocks/coachella-2024-synth.png",
    waves: [
      {
        id: 0,
        artist: "burna-boy",
        data: "assets/mocks/burna-boy-wave.png",
        wavesAddress: "0x0000000000",
        description: "Wave 1 description",
      },
      {
        id: 1,
        artist: "drake",
        data: "assets/mocks/drake-wave.png",
        wavesAddress: "0x0000000000",
        description: "Wave 2 description",
      },
      {
        id: 2,
        artist: "bad-bunny",
        data: "assets/mocks/bad-bunny-wave.png",
        wavesAddress: "0x0000000000",
        description: "Wave 3 description",
      },
      {
        id: 3,
        artist: "taylor-swift",
        data: "assets/mocks/taylor-swift-wave.png",
        wavesAddress: "0x0000000000",
        description: "Wave 4 description",
      },
    ],
  },
  // {
  //   address: "0x0000000000",
  //   eventName: "Lollapalooza Chicago 2024",
  //   tokenAddress: "0x0000000000",
  //   tokenId: 1,
  //   data: "assets/mocks/lollapalooza-chicago-2024-synth.png",
  //   waves: [
  //     {
  //       id: 0,
  //       artist: "Wizkid",
  //       data: "#000000",
  //       data: "assets/mocks/burna-boy-wave.png",
  //       wavesAddress: "0x0000000000",
  //       description: "Wave 1 description",
  //     },
  //     {
  //       id: 1,
  //       artist: "Kendrick Lamar",
  //       data: "#000000",
  //       data: "assets/mocks/drake-wave.png",
  //       wavesAddress: "0x0000000000",
  //       description: "Wave 2 description",
  //     },
  //     {
  //       id: 2,
  //       artist: "Sza",
  //       data: "#000000",
  //       data: "assets/mocks/bad-bunny-wave.png",
  //       wavesAddress: "0x0000000000",
  //       description: "Wave 3 description",
  //     },
  //     {
  //       id: 3,
  //       artist: "Taylor Swift",
  //       data: "#000000",
  //       data: "assets/mocks/taylor-swift-wave.png",
  //       wavesAddress: "0x0000000000",
  //       description: "Wave 4 description",
  //     },
  //   ],
  // },
];
