export const mockSynths: Synth[] = [
  {
    address: "0x0000000000",
    eventName: "Coachella",
    tokenAddress: "0x0000000000",
    tokenId: 0,
    image: "/assets/mocks/coachella-2024-synth.png",
    waves: [
      {
        id: 0,
        artist: "burna-boy",
        data: "/assets/mocks/burna-boy-wave.png",
        wavesAddress: "0x0000000000",
        description: "Wave 1 description",
      },
      {
        id: 1,
        artist: "drake",
        data: "/assets/mocks/drake-wave.png",
        wavesAddress: "0x0000000000",
        description: "Wave 2 description",
      },
      {
        id: 2,
        artist: "bad-bunny",
        data: "/assets/mocks/bad-bunny-wave.png",
        wavesAddress: "0x0000000000",
        description: "Wave 3 description",
      },
      {
        id: 3,
        artist: "taylor-swift",
        data: "/assets/mocks/taylor-swift-wave.png",
        wavesAddress: "0x0000000000",
        description: "Wave 4 description",
      },
    ],
  },
  {
    address: "0x0000000067",
    eventName: "Lollapalooza Chicago 2024",
    tokenAddress: "0x0000000000",
    tokenId: 1,
    image: "/assets/mocks/coachella-2024-synth.png",
    waves: [
      {
        id: 0,
        artist: "wizkid",
        data: "#000000",
        wavesAddress: "0x0000000000",
        description: "Wave 1 description",
      },
      {
        id: 1,
        artist: "kendrick-lamar",
        data: "#000000",
        wavesAddress: "0x0000000000",
        description: "Wave 2 description",
      },
      {
        id: 2,
        artist: "sza",
        data: "#000000",
        wavesAddress: "0x0000000000",
        description: "Wave 3 description",
      },
      {
        id: 3,
        artist: "taylor-swift",
        data: "#000000",
        wavesAddress: "0x0000000000",
        description: "Wave 4 description",
      },
    ],
  },
];
